$font = Hack Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/Wallpapers/samurai-cyberpunk-2077-3840x2160-12532.jpg
    blur_passes = 0
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgb(ffffff) rgb(ffffff) 0deg
    
    font_color = rgb(ffffff)
    font_family = $font
    
    placeholder_text = Password
    
    halign = center
    valign = center
    rounding = 0
}